const toNumber = (value) => {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
};

const score = (weights, factors) =>
  Number(
    factors
      .reduce(
        (total, [factor, multiplier]) =>
          total + toNumber(weights[factor]) * multiplier,
        0,
      )
      .toFixed(3),
  );

export const STATEWISE_WEIGHT_FORMULAS = {
  bestForNomads: [
    ["workInfrastructure", 0.2],
    ["internet", 0.15],
    ["costOfLiving", 0.2],
    ["safety", 0.1],
    ["visaFlexibility", 0.1],
    ["nomadCommunity", 0.15],
    ["healthcareCostIndex", 0.05],
    ["startupEcosystemScore", 0.03],
    ["airQualityIndex", 0.02],
  ],
  bestWorkInfrastructure: [
    ["workInfrastructure", 0.4],
    ["internet", 0.3],
    ["internalCommuting", 0.2],
    ["accessibility", 0.1],
    // ["visaFlexibility", 0.1],
    // ["safety", 0.05],
    // ["healthcareCostIndex", 0.05],
    // ["startupEcosystemScore", 0.03],
    // ["airQualityIndex", 0.02],
  ],
  mostAffordable: [
    ["costOfLiving", 0.5],
    ["purchasingPower", 0.2],
    ["visaCost", 0.2],
    ["inflationStability", 0.1],
  ],
  safestCities: [
    ["safety", 0.7],
    ["qualityOfLife", 0.2],
    ["airQualityIndex", 0.1],
    // ["costOfLiving", 0.1],
    // ["visaFlexibility", 0.08],
    // ["internet", 0.07],
    // ["workInfrastructure", 0.05],
    // ["nomadCommunity", 0.03],
    // ["startupEcosystemScore", 0.02],
  ],
  easyVisaLongStay: [
    ["visaFlexibility", 0.4],
    ["visaCost", 0.3],
    ["visaRenewalEase", 0.3],
    // ["healthcareCostIndex", 0.08],
    // ["nomadCommunity", 0.07],
    // ["internet", 0.05],
    // ["workInfrastructure", 0.05],
    // ["airQualityIndex", 0.03],
    // ["startupEcosystemScore", 0.02],
  ],
  strongNomadCommunity: [
    ["nomadCommunity", 0.65],
    ["meetupsEvents", 0.2],
    ["lifestyleEntertainment", 0.15],
    // ["costOfLiving", 0.1],
    // ["visaFlexibility", 0.08],
    // ["safety", 0.07],
    // ["healthcareCostIndex", 0.05],
    // ["airQualityIndex", 0.03],
    // ["startupEcosystemScore", 0.02],
  ],
  healthcareFriendly: [
    ["qualityOfLife", 0.7],
    ["healthcareCostIndex", 0.1],
    ["medicalInsuranceEase", 0.1],
    ["accessibility", 0.1],
    // ["visaFlexibility", 0.08],
    // ["internet", 0.07],
    // ["workInfrastructure", 0.05],
    // ["nomadCommunity", 0.03],
    // ["startupEcosystemScore", 0.02],
  ],
  startupBusinessOpportunities: [
    ["startupEcosystemScore", 0.45],
    ["workInfrastructure", 0.25],
    ["techTalentDensity", 0.2],
    ["incubators", 0.1],
    // ["visaFlexibility", 0.08],
    // ["costOfLiving", 0.07],
    // ["safety", 0.05],
    // ["healthcareCostIndex", 0.03],
    // ["airQualityIndex", 0.02],
  ],
  cleanAirEnvironment: [
    ["airQualityIndex", 0.4],
    ["safety", 0.15],
    ["healthcareCostIndex", 0.1],
    ["costOfLiving", 0.1],
    ["visaFlexibility", 0.08],
    ["internet", 0.07],
    ["workInfrastructure", 0.05],
    ["nomadCommunity", 0.03],
    ["startupEcosystemScore", 0.02],
  ],
  bestForRemoteWorkSetup: [
    ["internet", 0.5],
    ["workInfrastructure", 0.5],
    // ["nomadCommunity", 0.15],
    // ["costOfLiving", 0.1],
    // ["airportConnectivity", 0.1],
    // ["directInternationalFlights", 0.15],
  ],
  cheapestPlaces: [
    ["costOfLiving", 0.5],
    ["purchasingPower", 0.5],
  ],
  bestConnectedCitiesFlights: [
    ["directInternationalFlights", 0.5],
    ["airportConnectivity", 0.5],
    // ["internet", 0.1],
    // ["workInfrastructure", 0.1],
    // ["nomadCommunity", 0.1],
    // ["costOfLiving", 0.05],
  ],
  strongNomadCommunityWFA: [
    ["nomadCommunity", 0.7],
    ["startupEcosystemScore", 0.3],
    // ["workInfrastructure", 0.15],
    // ["airportConnectivity", 0.1],
    // ["directInternationalFlights", 0.1],
    // ["costOfLiving", 0.1],
  ],
  fastInternetCities: [
    ["internet", 0.7],
    ["workInfrastructure", 0.3],
    // ["nomadCommunity", 0.1],
    // ["airportConnectivity", 0.1],
    // ["directInternationalFlights", 0.1],
    // ["costOfLiving", 0.05],
  ],
  bestWorkInfrastructureWFA: [
    ["workInfrastructure", 0.6],
    ["internet", 0.2],
    ["startupEcosystemScore", 0.2],
    // ["airportConnectivity", 0.1],
    // ["directInternationalFlights", 0.05],
    // ["costOfLiving", 0.05],
  ],
  maximumSavings: [
    ["costOfLiving", 0.5],
    ["taxFriendly", 0.3],
    ["healthcareCostIndex", 0.2],
    // ["purchasingPower", 0.2],
    // ["inflationStability", 0.1],
    // ["startupSetupCost", 0.1],
  ],
  lowTaxation: [
    ["taxFriendly", 0.8],
    ["inflationStability", 0.2],
    // ["costOfLiving", 0.2],
    // ["purchasingPower", 0.2],
    // ["healthcareCostIndex", 0.1],
    // ["startupSetupCost", 0.05],
  ],
  purchasingPower: [
    ["purchasingPower", 0.6],
    ["costOfLiving", 0.3],
    ["taxFriendly", 0.1],
  ],
  financialStabilityLowRisk: [
    ["inflationStability", 0.7],
    ["costOfLiving", 0.1],
    ["taxFriendly", 0.1],
    ["purchasingPower", 0.1],
    // ["healthcareCostIndex", 0.2],
    // ["startupSetupCost", 0.1],
  ],
  startupSetupCost: [
    ["startupSetupCost", 0.7],
    ["taxFriendly", 0.15],
    ["costOfLiving", 0.15],
    // ["purchasingPower", 0.1],
    // ["inflationStability", 0.1],
    // ["healthcareCostIndex", 0.1],
  ],
  balancedFinancialLifestyle: [
    ["costOfLiving", 0.2],
    ["purchasingPower", 0.2],
    ["taxFriendly", 0.15],
    ["inflationStability", 0.15],
    ["healthcareCostIndex", 0.15],
    ["startupSetupCost", 0.15],
  ],
  socialPartyLifestyle: [
    ["partyLifestyle", 0.25],
    ["nightlife", 0.2],
    ["meetupsEvents", 0.15],
    ["nomadCommunity", 0.15],
    ["soloNomad", 0.1],
    ["founderNomads", 0.05],
    ["coupleNomads", 0.05],
    ["femaleNomads", 0.05],
  ],
  chillWellnessLifestyle: [
    ["yoga", 0.25],
    ["nature", 0.2],
    ["nomadCommunity", 0.15],
    ["soloNomad", 0.1],
    ["femaleNomads", 0.1],
    ["coupleNomads", 0.1],
    ["familyNomads", 0.1],
  ],
  adventureExploration: [
    ["adventure", 0.3],
    ["nature", 0.25],
    ["soloNomad", 0.15],
    ["nomadCommunity", 0.1],
    ["coupleNomads", 0.1],
    ["femaleNomads", 0.1],
  ],
  nomadCommunityNetworking: [
    ["nomadCommunity", 0.3],
    ["meetupsEvents", 0.2],
    ["founderNomads", 0.15],
    ["soloNomad", 0.1],
    ["coupleNomads", 0.1],
    ["femaleNomads", 0.1],
    ["partyLifestyle", 0.05],
  ],
  coupleFriendlyLifestyle: [
    ["coupleNomads", 0.35],
    ["nomadCommunity", 0.2],
    ["nature", 0.15],
    ["yoga", 0.1],
    ["safety", 0.1],
    ["meetupsEvents", 0.1],
  ],
  familyFriendlyLifestyle: [
    ["familyNomads", 0.3],
    ["safety", 0.2],
    ["nomadCommunity", 0.15],
    ["nature", 0.1],
    ["yoga", 0.1],
    ["healthcareCostIndex", 0.1],
    ["meetupsEvents", 0.05],
  ],
  femaleFriendlyLifestyle: [
    ["femaleNomads", 0.3],
    ["safety", 0.25],
    ["nomadCommunity", 0.15],
    ["soloNomad", 0.1],
    ["directInternationalFlights", 0.1],
    ["qualityOfLife", 0.1],
    // ["healthcareCostIndex", 0.05],
  ],
  founderNomads: [
    ["founderNomads", 0.3],
    ["nomadCommunity", 0.2],
    ["meetupsEvents", 0.15],
    ["startupEcosystemScore", 0.25],
    ["ventureCapital", 0.1],
    // ["coupleNomads", 0.05],
    // ["femaleNomads", 0.05],
  ],
  soloNomads: [
    ["soloNomad", 0.3],
    ["nomadCommunity", 0.2],
    ["meetupsEvents", 0.15],
    ["safety", 0.1],
    ["femaleNomads", 0.1],
    ["adventure", 0.1],
    ["partyLifestyle", 0.05],
  ],
  startupEcosystems: [
    ["startupEcosystemScore", 0.3],
    ["ventureCapital", 0.2],
    ["incubators", 0.15],
    ["techTalentDensity", 0.15],
    ["founderNomads", 0.1],
    ["conferences", 0.1],
  ],
  remoteJobOpportunities: [
    ["remoteJobs", 0.5],
    ["workInfrastructure", 0.15],
    ["nomadCommunity", 0.15],
    ["startupEcosystemScore", 0.2],
    // ["internet", 0.2],
    // ["costOfLiving", 0.1],
  ],
  founderNomadsAyc: [
    ["founderNomads", 0.3],
    ["conferences", 0.2],
    ["techTalentDensity", 0.2],
    ["startupEcosystemScore", 0.15],
    ["ventureCapital", 0.1],
    ["remoteJobs", 0.05],
  ],
  techTalentDensity: [
    ["techTalentDensity", 0.35],
    ["startupEcosystemScore", 0.2],
    ["conferences", 0.15],
    ["founderNomads", 0.1],
    ["ventureCapital", 0.1],
    ["nomadCommunity", 0.1],
  ],
  startupIncubatorsAccelerators: [
    ["incubators", 0.45],
    ["startupEcosystemScore", 0.2],
    ["founderNomads", 0.15],
    ["ventureCapital", 0.1],
    ["localGovernmentSupport", 0.1],
    // ["conferences", 0.1],
  ],
  balancedCareerGrowth: [
    ["remoteJobs", 0.3],
    ["workInfrastructure", 0.25],
    ["startupEcosystemScore", 0.2],
    ["ventureCapital", 0.15],
    ["localGovernmentSupport", 0.1],
    // ["conferences", 0.15],
  ],
  ventureCapitalPresence: [
    ["ventureCapital", 0.5],
    ["startupEcosystemScore", 0.1],
    ["incubators", 0.1],
    ["ventureCapitalInvestments", 0.3],
    // ["founderNomads", 0.1],
    // ["techTalentDensity", 0.1],
  ],
  conferencesEvents: [
    ["conferences", 0.25],
    ["founderNomads", 0.1],
    ["startupEcosystemScore", 0.25],
    ["ventureCapital", 0.1],
    ["techTalentDensity", 0.1],
    ["governmentStartupEvents", 0.2],
  ],
};

export const stateWiseWeightCalculation = (weight = {}) =>
  Object.fromEntries(
    Object.entries(STATEWISE_WEIGHT_FORMULAS).map(([formulaName, factors]) => [
      formulaName,
      score(weight, factors),
    ]),
  );
