version: '3.8'

services:
  # Next.js App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nomads-travel-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
